#!/bin/bash
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -q regular
#SBATCH -J cs267
#SBATCH -t 00:30:00

#run the application:
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 1000
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 2000
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 4000
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 8000
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 16000
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 32000
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 64000
srun -n 1 -c 1 --cpu_bind=cores ./serial -s 42 -n 128000

