#!/bin/bash
#SBATCH -N 1
#SBATCH -C knl
#SBATCH -q debug
#SBATCH -J cs267
#SBATCH -t 00:30:00

#OpenMP settings:
export OMP_NUM_THREADS=68
export OMP_PLACES=cores
export OMP_PROC_BIND=spread

#run the application:
echo "OpenMP Serial"
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 1000
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 2000
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 4000
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 8000
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 16000
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 32000
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 64000
srun -n 1 -c 68 --cpu_bind=cores ./openmp -s 42 -n 128000
